services:
  backend_java:
    build: ./DogRandomService
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dogs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  backend_c_sharp:
    build: ./DogRatingService
    ports:
      - "7000:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
    
      POSTGRES_DB: dogs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
